export const UNJUMBLE_SENTENCES = [
  "The sun rises in the east every morning .",
  "She likes to read books in the library .",
  "They represent the future of our country .",
  "Water boils at one hundred degrees Celsius .",
  "The quick brown fox jumps over the lazy dog .",
  "I have a meeting at two o'clock .",
  "Can you please pass me the salt ?",
  "He is the best player on the team .",
  "We are going to the beach this weekend .",
  "My favorite color is blue because it is calm .",
  "The cat sleeps on the sofa all day .",
  "Do you know how to cook pasta ?",
  "It acts as a barrier against the wind .",
  "She plays the piano beautifully in the concert .",
  "Birds fly south for the winter season .",
  "I need to buy some milk and eggs .",
  "The train arrives at the station on time .",
  "He studied hard for the mathematics exam .",
  "We should protect our environment for the future .",
  "The earth revolves around the sun .",
  "She wrote a letter to her grandmother .",
  "They are building a new house down the street .",
  "I usually drink coffee in the morning .",
  "The dog barked at the stranger at the door .",
  "Can we go to the park later ?",
  "He forgot his keys in the car .",
  "The flowers bloom in the spring time .",
  "I am learning directly from the experts .",
  "She wore a beautiful red dress to the party .",
  "They watched a movie at the cinema last night .",
  "I like to listen to music while I work .",
  "The baby cried when she was hungry .",
  "We visited the museum during our vacation .",
  "He runs five miles every single day .",
  "The teacher explained the lesson clearly .",
  "I want to travel the world someday .",
  "She is a doctor at the local hospital .",
  "They played soccer in the rain .",
  "I lost my phone somewhere in the house .",
  "The sky is clear and blue today .",
  "Can you help me with my homework ?",
  "He fixed the broken chair yesterday .",
  "We had a delicious dinner at the restaurant .",
  "The moon shines brightly in the night sky .",
  "She bought a new pair of shoes .",
  "They are planning a surprise party for him .",
  "I enjoy walking in the forest .",
  "The children are playing in the garden .",
  "Do you like strict rules or freedom ?",
  "He is reading a fascinating novel .",
  "We should respect other people's opinions .",
  "The car broke down on the highway .",
  "She speaks three languages fluently .",
  "They participated in the science fair .",
  "I prefer tea over coffee usually .",
  "The wind leaves the trees shifting .",
  "Can you answer the phone please ?",
  "He painted the wall white .",
  "We are waiting for the bus to arrive .",
  "The stars twinkle in the dark sky .",
  "She baked a cake for her birthday .",
  "They cleaned the house from top to bottom .",
  "I have an appointment with the dentist .",
  "The river flows into the ocean .",
  "Can you turn off the lights ?",
  "He is learning how to drive a car .",
  "We celebrated the victory with a party .",
  "The computer is running very slow today .",
  "She took a picture of the sunset .",
  "They organize the files by date .",
  "I need to charge my phone battery .",
  "The leaves turn orange in the autumn .",
  "Can you recommend a good book ?",
  "He found a coin on the ground .",
  "We look forward to meeting you soon .",
  "The clock on the wall has stopped .",
  "She listens to the radio every morning .",
  "They hiked up the mountain trail .",
  "I am writing a report for work .",
  "The snow covered the ground in white .",
  "Can you hear the birds singing ?",
  "He always keeps his promises .",
  "We enjoyed the performance very much .",
  "The map shows the way to the city .",
  "She smiles whenever she sees him .",
  "They moved to a new apartment recently .",
  "I forgot to water the plants today .",
  "The library is a quiet place to study .",
  "Can you open the window please ?",
  "He wears glasses to read clearly .",
  "We walked along the beach at sunset .",
  "The apple fell from the tree .",
  "She helps her mother in the kitchen .",
  "They argued about which movie to watch .",
  "I believe in the power of kindness .",
  "The bus stopped at the red light .",
  "Can you speak a little louder ?",
  "He dreams of becoming a pilot .",
  "We shared a pizza for lunch .",
  "The key opens the front door .",
];
